In [3]:
import tensorflow as tf

In [25]:
# A quick test to confirm control of weight initialization for reproducability
w = tf.random_normal([2,2], stddev=0.01, seed=15)

In [26]:
with tf.Session() as sess:
    print(sess.run(w))
    print(sess.run(w))
    print(sess.run(w))

[[ 0.00704577  0.00127421]
 [ 0.01059515  0.00423765]]
[[-0.00266967  0.00376094]
 [ 0.00349845 -0.01188294]]
[[ 0.00653669 -0.00612784]
 [ 0.01226894 -0.00452355]]


In [27]:
with tf.Session() as sess:
    print(sess.run(w))
    print(sess.run(w))

[[ 0.00704577  0.00127421]
 [ 0.01059515  0.00423765]]
[[-0.00266967  0.00376094]
 [ 0.00349845 -0.01188294]]


In [28]:
with tf.Session() as sess:
    print(sess.run(w))

[[ 0.00704577  0.00127421]
 [ 0.01059515  0.00423765]]
